POST http://localhost:3000/api/generate-licence HTTP/1.1
content-type: application/json

{
    "password": "ThePassword",
    "key_id": "test-2",
    "product_name": "Laravel 10 - Base Admin Panel",
    "product_id": "1"
}

###

POST http://localhost:3000/api/generate-licence HTTP/1.1
content-type: application/json

{
    "password": "ThePassword",
    "key_id": "test-2",
    "product_name": "Laravel 10 - Base Admin Panel",
    "product_id": "1",
    "expiration_time": "1h"
}

###

POST http://localhost:3000/api/revoke-licence HTTP/1.1
content-type: application/json

{
    "password": "ThePassword",
    "key_id": "test-2"
}

###

GET http://localhost:3000/api/licences HTTP/1.1
content-type: application/json
